### ISSUE TITLE
VaMenu component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2935] opened 2023-02-09 10:08 UTC
Probably would be used in context of dropdown.
We may be able to reuse some of its styling in select.
Also see https://github.com/epicmaxco/vuestic-ui/issues/2619#issuecomment-1416536679

**Comment by m0ksem** [comment] 2023-07-08 20:25
Duplicate of https://github.com/epicmaxco/vuestic-ui/issues/1417

**Closed by m0ksem** 2023-07-08 20:25 UTC
Labels: research
