### ISSUE TITLE
`VaSelect` can't be focused with a `content` slot

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#1956] opened 2022-06-17 06:24 UTC
**Vuestic-ui version:** 1.4.1

**Steps to reproduce**
  - https://vuestic.dev/en/ui-elements/select#slots

**What is the current behavior?**
  - can't be focused when `content` slot
  
![chrome-capture-2022-5-17](https://user-images.githubusercontent.com/55198465/174238055-65ebf3ec-6040-41c9-9def-c4fb18f3045b.gif)

**Comment by m0ksem** [comment] 2022-06-19 00:34
Duplicate of https://github.com/epicmaxco/vuestic-ui/issues/1839

**Closed by m0ksem** 2022-06-19 00:34 UTC
Labels: BUG
