### ISSUE TITLE
Ability to select() va-input

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1877] opened 2022-05-30 20:42 UTC
- [ ] add `select` method

Bonus points:
- [ ] Check other components as to whether they support native events (select, textarea, checkbox etc)

**Comment by m0ksem** [comment] 2023-02-22 20:10
Duplicate of https://github.com/epicmaxco/vuestic-ui/issues/1609

**Closed by m0ksem** 2023-02-22 20:10 UTC
Labels: FEATURE, EXTERNAL
