### ISSUE TITLE
VaImage doesn't show image on ssr

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2488] opened 2022-10-11 15:58 UTC
**Vuestic-ui version:** 1.5.0

![image](https://user-images.githubusercontent.com/5394573/195140968-0e53db69-9e3f-4d9d-a609-1ed4177f5abf.png)

In component `loading` is set to `true` which sets `display: none`. `loading = false` is set on image load, but for some reason image load doesn't happen (on client)

**Comment by asvae** [comment] 2022-10-18 09:52
I set loading to false by default, but error case still doesn't work on SSR.

**Comment by kilakewe** [comment] 2023-02-15 21:49
I'm still seeing this same issue in nuxt using SSR for the va-image component. 

Versions: 
    "nuxt": "^3.2.0",
    "@vuestic/nuxt": "^1.0.10",
    "vuestic-ui": "0.0.0-experimental-5cff9945d-20230214"

**Comment by aluarius** [comment] 2023-02-16 11:07
@kilakewe unfortunately, I can't reproduce this problem for mentioned stack. Can you provide more information - part of code with VaImage usage, for example.

**Comment by aluarius** [comment] 2023-02-16 11:08
@rustem-nasyrov if you have time, test it too please, just to be sure.

**Comment by aluarius** [comment] 2023-02-23 08:35
I will close it for now. Will reopen in case of new information.

**Closed by aluarius** 2023-02-23 08:35 UTC
Labels: BUG, HIGH PRIORITY, difficulty 3: medium, value 5: lifechanger
