### ISSUE TITLE
1.2.2+ vuestic-ui fails to execute in some cases

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-ui#1091] opened 2021-09-14 14:09 UTC
* **What is the expected behavior?**
Vuestic-ui should work without errors.

* **Steps to reproduce:**
* Open `vuestic-admin`
* Update `vuestic-ui` to `1.2.2+` version ( feel free to check others as well )
* Start local server

![withConfigTransportError](https://user-images.githubusercontent.com/7745899/133272534-b7e60417-2348-4aa5-a370-a8b42a191ce8.png)

**Comment by m0ksem** [comment] 2021-09-16 12:36
This problem was caused by @vue/compiler-sfc package. Updating `vue` to version ^3.2.0 and `@vue/compiler-sfc` to ^3.2.0 solved the issue.

@untael. Should be helpful. Please, close this issue if it helps!

**Closed** 2021-09-16 21:50 UTC
Labels: bug, high priority
