### ISSUE TITLE
Errors on docs build

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3436] opened 2023-05-22 16:45 UTC
**Vuestic-ui version:** 1.6.4

**Steps to reproduce**

run `buid:docs:ci` from project roo

**What is the expected behavior?**

not seeing errors

**What is the current behavior?**

see a lot of errors like this
<img width="969" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/5394573/a63252cd-1040-4fee-8412-3409fe22a95a">

**Other information**

I'm not sure if this affects anything. But it's better to check, probably something simple on our side.

Also take note of #3425, we won't have docs in a bit so no reason to fix if this is language bug.

**Comment by m0ksem** [comment] 2023-05-22 21:09
This errors caused by localize plugin for markdown. If we remove localization we can remove this plugin and close this issue. So this is a low priority issue.

**Closed** 2023-05-25 14:15 UTC
Labels: BUG, docs, good first issue, build, difficulty 2: easy, value 1: minor
