### ISSUE TITLE
Vertical tab slider broken

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-ui#1245] opened 2021-11-18 11:37 UTC
![aJAcsQpr3C](https://user-images.githubusercontent.com/23530004/142408301-2f83079b-484f-440a-b257-54ec27ad3ab8.gif)

**Comment by asvae** [comment] 2021-11-25 09:37
@m0ksem how do you reproduce this?

**Comment by ishpartko** [comment] 2021-11-26 17:28
I can't reproduce :(

**Comment by m0ksem** [comment] 2021-11-26 19:59
@asvae, @ishpartko This issue can be reproduced in Firefox. In Chrome, it works fine for me too.

**Comment by Derranion** [comment] 2021-12-27 16:35
Was not able to reproduce - do not see this issue on vuestic.dev as well:
https://vuestic.dev/en/ui-elements/tabs#vertical-alignment

That's why I'll close this one.

But we have another vertical tab issue (looks like it may be related to `Vite`) going to create it soon.

**Closed by Derranion** 2021-12-27 16:35 UTC
Labels: BUG, LOW PRIORITY, no repro
