### ISSUE TITLE
The conventions link is not working

### ISSUE THREAD

**Issue by sergey-kravcov** [epicmaxco/vuestic-ui#920] opened 2021-07-05 10:22 UTC
* **What is the expected behavior?**
This link should go to the next url: https://github.com/epicmaxco/vuestic-ui/blob/master/packages/docs/conventions.md

* **What is the current behavior?**
The link can be found here: http://localhost:8081/en/contribution/guide#for-core-contributors
The conventions link is not working

![Снимок экрана 2021-07-05 в 13 21 10](https://user-images.githubusercontent.com/20461547/124457034-0b55c200-dd94-11eb-9a10-c46a40b2d655.png)

**Comment by DieselTripleX** [comment] 2021-07-05 11:08
Duplicate of #896

**Closed** 2021-07-06 06:19 UTC
Labels: triage
