### ISSUE TITLE
With closed dev-tools new docs do not work properly

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#3194] opened 2023-03-17 12:39 UTC
**Vuestic-ui version:** 1.6.2

* Go to https://vuestic-ui.up.railway.app/en/styles/colors, then navigate through pages.

Result:
* no navigation happening, I stay on the same page

Expecting:
* navigation to work

We have to fix that before we move docs to railway fully.

**Comment by m0ksem** [comment] 2023-03-17 15:36
@asvae, please, double check if it fixed on https://develop.vuestic.dev/getting-started/tree-shaking

**Comment by m0ksem** [comment] 2023-04-19 15:11
Likely fixed somewhere... Not able to reproduce it anymore.

**Closed by m0ksem** 2023-04-19 15:11 UTC
Labels: BUG
