### ISSUE TITLE
VaToast title color, icon name

### ISSUE THREAD

**Issue by RVitaly1978** [epicmaxco/vuestic-ui#3870] opened 2023-09-14 10:45 UTC
**Vuestic-ui version:** 1.8.0

1. title color does not adjust to toast color 

<img width="437" alt="image" src="https://github.com/epicmaxco/vuestic-ui/assets/55198465/c3bb7a9b-95b8-4633-9f42-9a1331cb2586">

![image](https://github.com/epicmaxco/vuestic-ui/assets/55198465/a9b46e10-58cd-4743-b68c-a74c12e9df73)

2. icon name should be **va-close**

![image](https://github.com/epicmaxco/vuestic-ui/assets/55198465/2cb042e0-20b4-43ab-9157-b69233a52f41)

**Comment by m0ksem** [comment] 2023-09-15 07:02
Duplicate of https://github.com/epicmaxco/vuestic-ui/issues/3866

**Closed by m0ksem** 2023-09-15 07:02 UTC
Labels: BUG
