### ISSUE TITLE
Move sticky search from nuxt version

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1939] opened 2022-06-14 07:36 UTC
It's already implemented in nuxt folder, let's backport it to regular docs.

**Comment by m0ksem** [comment] 2022-07-04 10:16
Details: We need to move search from Sidebar to sticky Header. Choose better position. 
![image](https://user-images.githubusercontent.com/23530004/177134512-2d7d96d0-2a10-491c-866c-84d813ea9a47.png)

Bonus tip: Add keybind like `ctrl K`

**Comment by m0ksem** [comment] 2022-07-08 23:04
Duplicate of https://github.com/epicmaxco/vuestic-ui/issues/726

**Comment by damirJa** [comment] 2022-07-11 13:56
@m0ksem I would like to implement `keybind`, but I realised what we are using v2 of the `DocSearch`, so the `keybind` will only be able to focus on the input field and it's seems not very useful. I feel like it would be a cool feature to open search window like here. But we need to update `DocSearch` probably
<img width="1098" alt="CleanShot 2022-07-11 at 18 52 13@2x" src="https://user-images.githubusercontent.com/10356386/178279872-1446f585-12bb-4189-9851-8de0f866fc6e.png">

**Closed** 2022-07-13 20:33 UTC
Labels: BUG, good first issue
