### ISSUE TITLE
On hover - "Open in Github" button is barely visible

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#2282] opened 2022-08-22 15:08 UTC
All other buttons are ok.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/5394573/185955026-336fbc25-3c0c-4d82-9594-d08ed0449c5b.png">

**Comment by m0ksem** [comment] 2022-08-22 16:31
> From which file is this exactly from ?

Hey, @Pathholder1806. This issue is related to DocsExample component. You can find reproduction on any demo we have in docs: https://vuestic.dev/en/ui-elements/alert#default

**Comment by Pathholder1806** [comment] 2022-08-22 17:25
The issue is persisting with all the 'a tags'

**Comment by Pathholder1806** [comment] 2022-08-22 17:31
So the issue is in the following file:
https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/styles/typography/_mixins.scss
Line number - 183

The value of brightness filter on hover is too high.

**Comment by Pathholder1806** [comment] 2022-08-22 17:37
@m0ksem 
**filter: brightness(100%)** should fix the issue.
File - https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/styles/typography/_mixins.scss
Line - 183

**Comment by asvae** [comment] 2022-08-22 22:52
Might be related to #2260. Global typography is giving us issues.

**Comment by aluarius** [comment] 2022-08-23 10:25
Closed via https://github.com/epicmaxco/vuestic-ui/pull/2288

**Closed by aluarius** 2022-08-23 10:25 UTC
Labels: BUG, good first issue
