### ISSUE TITLE
Doesn't work with nuxt 3

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-ui#1487] opened 2022-02-07 00:33 UTC
See [Issue in nuxt 3 repo](https://github.com/nuxt/framework/discussions/1869).

We want to focus on making it work in context of nuxt 3, not getting all components functional (which we can do in context of #650)

**Comment by m0ksem** [comment] 2022-02-07 11:12
Removing `vue-property-decorator` should make a trick. https://github.com/epicmaxco/vuestic-ui/issues/1397

```ts
@Ref() readonly htmlInput!: HTMLInputElement
```

compiles to 

```ts
n.__decorate([Ref("htmlInput"),n.__metadata("design:type",HTMLInputElement)]
```

I have tried to change type to any and the issue is gone. But, there are a lot of `@Ref` usages

**Comment by m0ksem** [comment] 2022-05-05 10:19
closed in https://github.com/epicmaxco/vuestic-ui/pull/1501

**Closed by m0ksem** 2022-05-05 10:19 UTC
Labels: BUG, EXTERNAL
