### ISSUE TITLE
Components arent following global config in build.

### ISSUE THREAD

**Issue by niddey** [epicmaxco/vuestic-ui#1042] opened 2021-08-21 17:26 UTC
* **What is the expected behavior?**
![Expected behavior](https://user-images.githubusercontent.com/11835614/130329998-c5b31888-69d2-4877-b7f6-16c5b1a076ca.png)
The components follow configs set with mergeGlobalConfig.
Screenshot from npm run serve output.

* **What is the current behavior?**
![Current behavior](https://user-images.githubusercontent.com/11835614/130330000-98e81a28-1d48-4bd7-a9c9-8c64edefc540.png)
The components ignore the config.
Screenshot from npm run build output.

* **Steps to reproduce, ideally also a screenshot or gif if it's a style issue**
Clone vuestic-admin from git.
Run _npm install vuestic-ui_ to upgrade to latest version. Remove epic-spinners if needed as it wants Vue 2.
Then look at page output of build and serve commands.

* **Other information** 
Probalbly related: #1006

**Comment by Derranion** [comment] 2021-09-12 22:24
Global config size issue should be resolved by this pull request:

- [Fix #1054: GlobalConfig sizes, temporary solution #1088](https://github.com/epicmaxco/vuestic-ui/pull/1088)

Going to check it and resolve the rest config issues next morning.

**Comment by Derranion** [comment] 2021-09-15 16:27
Sizes now will work as expected but we have found another bug [1.2.2+ vuestic-ui fails to execute in some cases](https://github.com/epicmaxco/vuestic-ui/issues/1091) so we will need to wait a bit for a fix.

WithConfigTransport also has some problems after the build so I will leave this issue opened until full resolution to not create a new one.

**Comment by Derranion** [comment] 2021-09-16 16:35
The source of the problem is that bundlers rename `'name' option` of the components if they use 'vue-class-component' inside. 

Looks like `@Options` syntax of vue-class-component causes this behavior.

**Closed** 2021-09-17 15:19 UTC
Labels: bug
